sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

script:
  - docker image build -f Dockerfile -t brunokarpo/playing:latest -t brunokarpo/playing:$SHA  .

after_success:
  - docker push brunokarpo/playing:latest
  - docker push brunokarpo/playing:$SHA