apiVersion: v1
kind: Service
metadata:
  name: playing-application-cluster-ip
  namespace: playing-application
spec:
  type: ClusterIP
  selector:
    component: backend
  ports:
    - port: 8080
      targetPort: 8080