apiVersion: v1
kind: ConfigMap
metadata:
  name: playing-application-config-map
  namespace: playing-application
data:
  SERVER_PORT: "8080"
  SERVER_CONTEXT: /playing
  MANAGEMENT_SERVER_PORT: "8081"
  MANAGEMENT_SERVER_CONTEXT: /
  MANAGEMENT_ENDPOINT_WEB_PATH: /
  MANAGEMENT_ENDPOINT_EXPOSURE: "health,info,metrics"