apiVersion: v1
items:
  - apiVersion: autoscaling/v1
    kind: HorizontalPodAutoscaler
    metadata:
      name: playing-application-hpa
      namespace: playing-application
    spec:
      maxReplicas: 10
      minReplicas: 2
      scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: playing-application-deployment
      targetCPUUtilizationPercentage: 50
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""